# Generated by Django 2.2.7 on 2020-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
