# Generated by Django 2.2.7 on 2020-03-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200331_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
    ]
