# Generated by Django 2.2.7 on 2020-03-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200331_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
