# Generated by Django 2.2.7 on 2020-01-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200129_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
