# Generated by Django 2.2.7 on 2020-04-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_musician_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musician_region', to='app.Musician'),
        ),
    ]
