# Generated by Django 2.2.7 on 2020-02-08 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_remove_musician_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='musician_pics'),
        ),
        migrations.AddField(
            model_name='musician',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
