# Generated by Django 2.2.7 on 2020-02-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200208_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='phone_number',
        ),
    ]
