# Generated by Django 2.2.7 on 2020-02-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_musician_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='city',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='password',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='playing_level',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='user_name',
        ),
    ]
