# Generated by Django 2.2.7 on 2020-04-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200404_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='region',
        ),
    ]
