# Generated by Django 2.2.7 on 2020-04-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('app', '0009_remove_musician_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region'),
        ),
    ]
