# Generated by Django 2.2.7 on 2020-04-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_musician_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='region',
        ),
    ]
