# Generated by Django 2.2.7 on 2020-04-08 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_musician_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^(05)[0-4][0-9]{7}$')]),
        ),
    ]
