# Generated by Django 2.2.7 on 2020-05-04 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_musician_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^(05)[0-4][0-9]{7}$')]),
        ),
    ]
