# Generated by Django 2.2.7 on 2020-02-29 20:59

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200229_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='playing_level',
            field=models.IntegerField(choices=[(1, 'MASTER'), (2, 'HIGH'), (3, 'MEDIUM'), (4, 'LOW')], default=app.utils.PlayingLevelTypes(4)),
        ),
    ]
