# Generated by Django 2.2.7 on 2020-03-23 12:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_musician_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='first_name',
            field=models.CharField(default='---', max_length=200),
        ),
        migrations.AddField(
            model_name='musician',
            name='last_name',
            field=models.CharField(default='---', max_length=200),
        ),
        migrations.AddField(
            model_name='musician',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='---', max_length=128, region=None, unique=True),
        ),
    ]
