# Generated by Django 2.2.7 on 2020-03-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200323_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='phone',
        ),
    ]
