# Generated by Django 2.2.7 on 2020-03-24 16:09

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200323_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.IntegerField(blank=True, choices=[(1, 'GUITAR'), (2, 'DRUMS'), (3, 'BASS'), (4, 'KEYBOARDS')], default=app.utils.InstrumentTypes(1), null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='playing_level',
            field=models.IntegerField(blank=True, choices=[(1, 'MASTER'), (2, 'HIGH'), (3, 'MEDIUM'), (4, 'LOW')], default=app.utils.PlayingLevelTypes(4), null=True),
        ),
    ]
