# Generated by Django 2.2.7 on 2020-03-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200324_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(default='---', max_length=20),
        ),
    ]
