# Generated by Django 2.2.7 on 2020-03-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200324_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
    ]
