# Generated by Django 2.2.7 on 2020-03-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200324_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='birthday',
        ),
    ]
