# Generated by Django 2.2.7 on 2020-03-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_musician_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
